- 'compute_environment': 'LOCAL_MACHINE'
- 'deepspeed_config': None
- 'distributed_type': 'TPU'
- 'machine_rank': 0
- 'main_process_ip': None
- 'main_process_port': None
- 'main_training_function': 'main'
- 'mixed_precision': 'fp16'
- 'num_machines': 1 
- 'num_processes': 1
- 'use_cpu': True
